version: '3.6'

volumes:
  caddy: {}

networks:
  caddy:
    external: true

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    hostname: caddy
    env_file:
      - './env/common.env'
    ports:
      - 80:80
      # - 443:443
    volumes:
      - caddy:/data
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${USERDIR}/volumes/caddy/shared/stuff:/shared/stuff
    networks:
      - caddy
