global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 10s

remote_write:
 - url: "http://victoria-metrics:8428/api/v1/write"

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: vmagent
    honor_timestamps: true
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'vmagent:8429'

  - job_name: cadvisor
    honor_timestamps: true
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cadvisor:8080'

  - job_name: caddy
    honor_timestamps: true
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'caddy:2020'

  - job_name: node-exporter
    honor_timestamps: true
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: victoria-metrics
    honor_timestamps: true
    static_configs:
      - targets:
        - 'victoria-metrics:8428'

  - job_name: grafana
    honor_timestamps: true
    static_configs:
      - targets:
        - 'grafana:3000'
