version: '3.6'

networks:
  storage:
    external: true

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    expose:
      - '5432'
    env_file:
      - '../env/common.env'
      - '../env/postgres.env'
    networks:
      - storage

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    restart: always
    env_file:
      - '../env/common.env'
    expose:
      - '8428'
    volumes:
      - '${USERDIR}/volumes/victoria-metrics/data:/victoria-metrics-data:z'
    networks:
      - storage
